version: '3.8'

services:
  chatbot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-chatbot
    ports:
      - "8501:8501"  # Streamlit port
    volumes:
      - .:/app
      - .streamlit:/app/.streamlit  # Mount Streamlit secrets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

networks:
  default:
    name: ai-chatbot-network
    driver: bridge 